sudo: required
services: 
  - docker

before_install: 
  - docker build -t dex83/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dex83/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-eu-north-1-485841952238"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

